### ISSUE TITLE
Add signing of published OCI images with cosign

### ISSUE THREAD

**Issue by devantler** [devantler/roadmap#8]
### Description

The published OCI Artifacts should be signed with cosign as part of the `publish.yaml` pipeline.

Avisi Cloud provides [a guide](https://github.com/avisi-cloud/cosign-tutorial) for the purpose

### Tasklist

- [ ] Create a cosign key, and store it in `devantler/dotfiles`
- [ ] Add the cosign key and password to GitHub secrets in `devantler/oci-artifacts` and `devantler/homelab`
- [ ] Enhance the `publish.yaml` pipeline in `devantler/oci-artifacts` and `devantler/homelab` with cosigning capabilities.
